### ISSUE TITLE
Docker Pull fails with error: denied

### ISSUE THREAD

**Issue by bolderbast** [jehy/hass-dbstats#1]
Hi!
Love the idea of this project, and I am trying to get this up and running.
However, I'm running into an issue.

Configured docker-compose.yml as per documentation:

```yaml
version: '3.9'

services:  

  hass-dbstats:
    container_name: dbstats
    image: "ghcr.io/jehy/ha-dbstats:latest"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/home-assistant/config:/homeassistant:ro
```

when issuing the `docker-compose up -d` command, the following error is presented:

`Error response from daemon: Head "https://ghcr.io/v2/jehy/ha-dbstats/manifests/latest": denied`

A quick internet search suggests that the image might be marked "private"?
