### ISSUE TITLE
Make container image available for ARM64

### ISSUE THREAD

**Issue by Un4Cn** [jehy/hass-dbstats#4]
Hi!

I've found this nice add-on that you created in the Home Assistant forums:
[https://community.home-assistant.io/t/dbstats-addon-for-database-usage-analytics/685401](https://community.home-assistant.io/t/dbstats-addon-for-database-usage-analytics/685401)

I wanted to try it out on my Home Assistant setup, but unfortunately it does not work. The container starts and keeps giving the error:
`exec /usr/local/bin/docker-entrypoint.sh: exec format error`
This is usually an indication of running a container on an unsupported architecture.

In my case there is no supervisor  or anything, I just run all Home Assistant containers on a Raspberry Pi 5, which has the ARM64 arch.

Could you please build the image also for ARM64?

I don't see an `arm64` tag available for the image, so I think it's currently unavailable: [https://github.com/jehy/hass-dbstats/pkgs/container/hass-dbstats](https://github.com/jehy/hass-dbstats/pkgs/container/hass-dbstats)

**Comment by jehy** [comment]
Hi! Arm64 is same as aarch64 ( https://en.wikipedia.org/wiki/AArch64 ) - so it should work fine.

Did you try running it as addon, or as docker image?

Addon is being build for all artchiterctures ( https://github.com/jehy?tab=packages&repo_name=hass-addons ), but I only build simple docker standalone image for amd64 .

**Comment by Un4Cn** [comment]
Thank you for your reply.

I'm not sure how to force the aarch64...

I run it as docker container, here is the Docker Compose snippet:
```
hass-dbstats:
    container_name: home-assistant-dbstats
    image: "ghcr.io/jehy/hass-dbstats:0.3.22"
    restart: unless-stopped
    ports:
      - "8054:3000"
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - home-assistant-config:/homeassistant:ro
```

The error that I get inside the running container (`exec /usr/local/bin/docker-entrypoint.sh: exec format error`) is a clear indication that the architecture is not the right one. I've had this problem before with other containers and the fix was always to use the arm64 version of the Docker image.

I can't run it as addon, since I don't have add-on store available, I run everything as containers.

If my assumption is correct that the lack of arm64 version is the problem, then pretty much all Raspberry Pi 5 owners cannot run this add-on as a Docker container :(

Would it be problematic to build it for arm64 as well?
